name: frontend CI

on:
  push:
    branches:
     - main
  
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "frontend working fine"
